### ISSUE TITLE
last Will

### ISSUE THREAD

**Issue by hi-flyer** [Garadget/firmware#10]
I do not see it but does the device support last will?
or does aev put out the alert on mqtt (in mqtt only mode) if aev configured for online and offline?
tia

**Comment by yeti7** [comment]
I checked the code and in current version last will is not used, but the underlying code supports that. There is a version of f_connect call with additional parameters:

https://github.com/Garadget/firmware/blob/03d03a272ccb73d751304761590ec87116e1941b/src/lib/MQTT.h#L157

**Comment by hi-flyer** [comment]
Can I suggest that in the next issued version of garadget, it support the LWT as it seems a minor change. It would be definitely useful in the version I am developing for the plugin for nymea. Currently, I need to status it regularly to detect unexpected disconnect. it works but not really desirable.

**Comment by hi-flyer** [comment]
I have created a pull request to implement the LWT. Any chance it will be reviewed and hopefully approved?

**Comment by yeti7** [comment]
Did you have a chance to compile and flash the update firmware?
Did it work with the target system the way you expected?

**Comment by hi-flyer** [comment]
Yes it is compiled and works fine on my system. I have been monitoring it since the last update with zero issues 29 days ago.

**Comment by hi-flyer** [comment]
in case I did not answer the questions you posed as you expected:
Yes I did compile
Yes I did flash
Yes it does work on the target system as expected.

**Comment by yeti7** [comment]
All set. Thank you!

**Comment by hi-flyer** [comment]
Thank you.
Just read the Documentation and saw you updated it. I should have suggested that as well.
have a good day.
