### ISSUE TITLE
remote reset

### ISSUE THREAD

**Issue by hi-flyer** [Garadget/firmware#12]
I recently had an issue where the device was always responding that the door was closed and it was alway showing that the the system was sensing it was always night (ie the brightness value). The solution was to reset the garadget. Not a big problem but I was wondering if there was a remote signal I could send to force the reset of the device from the mqtt commands? ps not asking for a change. I get a lot of power flashes and suspect it was the cause of the issue.
thanks

**Comment by yeti7** [comment]
Sorry, there is no remote reset command implemented in current firmware.
This is something that can be implemented if somebody wants to fork/pull.
