### ISSUE TITLE
Brightness vs sensing

### ISSUE THREAD

**Issue by hi-flyer** [Garadget/firmware#13]
I have west facing windows in my garage. A consequence is I have a long paper tube around the garadget to reduce ambient light levels to minimize false detections. The Brightness level when hitting above 95% causes confusing on the Sensor detection levels. Attached Graph shows 3 days of tracking at a 5 min interval. Question is there some way to lower the brightness level (beyond the tube) as it appears the detection does not like the high level of brightness being detected.
![Garadget](https://user-images.githubusercontent.com/4342834/175318180-63dc108f-cc45-48ed-8c79-762b3d54e1f2.jpg)

**Comment by yeti7** [comment]
You can move sticker on the door to the location further away from the window. This way less light will get through the aperture.

**Comment by hi-flyer** [comment]
actually did not work. Moved the sticker above the door and the brightness level is still above 95% during the day. In an effort to improve that is when I put the ~ 8" long paper tube on the sensor. that drove up the night time values from ~ 20% to what you see on the graph (ie that really did not make sense to me unless the laser is somehow interacting with the tube). The daytime brightness stayed above the 95% level.
any other suggestions?
appreciate the feedback.

**Comment by yeti7** [comment]
Try reducing the size of the opening at the end of the tube. Also making sure the inside of it is dark and non-reflective might help.
