### ISSUE TITLE
Garadget Community website

### ISSUE THREAD

**Issue by hi-flyer** [Garadget/firmware#16]
I am getting the following message from firefox when I try to access https://community.garadget.com
Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for community.garadget.com. The certificate is only valid for community-backup.garadget.com.
 
Error code: SSL_ERROR_BAD_CERT_DOMAIN
 
View Certificate
has the community moved or does someone need to fix the certificate.
Sorry, I know this is not the right place to post this but not sure where to post. Hoping you can help

**Comment by yeti7** [comment]
Apologies for the disruption.
Had a server issue, had to spin off a new instance and restore from the backup. Should be all good now.
Might need to deal with notifications; expect to have that fixed later tomorrow.
