### ISSUE TITLE
magnetic sensor firmware

### ISSUE THREAD

**Issue by shereefalkady** [Garadget/firmware#4]
please forgive my ignorance... i got the normally-closed bin and i got the dfu utility but i have no idea to change the firmware

**Comment by h4rdc0d3d** [comment]
Hi there, all you need to know is how to flash particle devices over serial, using the USB-cable:
https://docs.particle.io/tutorials/developer-tools/cli/#flashing-over-serial-for-the-electron
This tutorial works for all particle devices and does not just apply for the Electron. Let me know if this works for you. Regards, Tim

**Comment by shereefalkady** [comment]
Well I do flash it using that method- and it does accept the flash - but does not function as required: with magnetic sensor

Also only the very first two pins (furthest from the USB) are the ones that give any sort of response ...

**Comment by shereefalkady** [comment]
Do I need to do anything other than flash the normally open or normally close firmware

**Comment by yeti7** [comment]
For pinout, sensor suggestions and other information about using Garadget with the gates, please visit the community board: https://community.garadget.com/tags/gate

**Comment by shereefalkady** [comment]
Hello Denis ... have you added location based auto open yet..

**Comment by yeti7** [comment]
This is currently available through IFTTT integration: https://ifttt.com/applets/gnpEk4y8-open-garage-on-arrival Please keep in mind that this feature relies on your phone's location services and has its limitations.
