### ISSUE TITLE
Home Assistant help

### ISSUE THREAD

**Issue by nelsonblaha** [Garadget/firmware#5]
Would it make sense to put the latest MQTT home assistant configuration on this readme somewhere? It's a common use case and the latest I found at the forum was out of date: 

https://community.garadget.com/t/mqtt-support/3226/59

I'd be happy to contribute my configuration, currently working under hassio 0.96.4

Seems like an authoritative working configuration here would be practical.

**Comment by yeti7** [comment]
Sorry, didn't get the notification about this.
MQTT configuration is discussed in [this topic](https://community.garadget.com/t/mqtt-support/3226), but your pull request for the readme is welcome. Please submit and I'll promptly review/approve.
