### ISSUE TITLE
http access

### ISSUE THREAD

**Issue by hi-flyer** [Garadget/firmware#9]
What would it take to be able to receive the configuration parameters (e.g. broker ip, broker port, broker username, broker password and nme) via http when on mqtt only and when the device already has the wifi parameters and is logged into the the local network. 

If you are going to tell me no because of security, then what would it take to receive a http request to initiate the configuration setup status over to the broker for then possible reconfiguration via existing broker commands. This might need an additional parameter being emitted in the configuration status message showing the device id to indicate it is a response to the http request for positive identification in a multi-garadget device scenario.

This is for a special case I am working on and am exploring my options (ie modify garadget or play tricky stuff in nymea that I am building a plugin for). 

thanks for any insight you can give.

**Comment by mzanetti** [comment]
Some more details on this:

nymea provides a MQTT broker which can be used in a regular manner. That is, the user would enter the setup mode on the garadget device and configure MQTT so the garadget would connect to it. Then the user would go to the nymea setup and configure the garadget integration to pick it up from the MQTT broker. This would work just fine.

However, in nymea, we always strive to make things as easy as possible for the user and ideally a user would not even need to know what MQTT is, it should just happen automagically. For that, nymea supports a concept of "MQTT channels" which is used with other ESP based devices such as tasmota or Shelly: nymea discovers the device in the network (normally using mDNS) and creates a MQTT channel on the internal broker. That means, a user/pass/clientId policy is generated for that particular device and subscription/topic filters are generated in a way that the device would be able to talk to the integration plugin in an isolated manner. Policies would prevent other clients on the same MQTT broker from snooping in on the traffic etc.
After generating that "channel", nymea would do a REST call to the device's config web interface and set all the details required for the MQTT connection. The user only needs to provide the login credentials for the webinterface to nymea and not bother with anything related to MQTT.

This would be our preferred solution, given the ease of use. The problem we're facing now, is that garadget seems to only provide the configuration web interface on the builtin WiFi AP in setup mode. I can see why it's this way, actually I think it's pretty neat from a security point of view. However, this compromises on ease of use and requires knowledge about networking and MQTT from the user.

The other option would probably to use the particle API through the cloud to configure the MQTT settings at runtime, but in nymea we always try to go for a no-cloud approach if possible at all so we'd rather not go this way.

So, what would be your thoughts on this? Do you think it'd be an option to provide the config web interface also during normal operation (or just some other REST based call to the device to configure MQTT)? From our point of view it could (perhaps even should) also be password protected, but I figure you didn't want the user to have to fiddle with additional credentials, hence hiding the config interface when not in AP mode.

We can go for the manual MQTT setup method, but before we do, we thought we'd ask if you'd be open to extend garadget to also support the more automated method.

**Comment by yeti7** [comment]
Michael,
What you described is possible but it's very specific feature for specific use case that requires more than just a code tweak.
Luckily, Garadget is open source and consumer-programmable so I would encourage you to fork the repo and try making mods to the code. I also have a hardware revision of garage controller based on ESP32 (in quantity). If that is more friendly territory, please PM me and we'll figure out how to make use of those in your project.

**Comment by hi-flyer** [comment]
Michael, one of the things that has to be done to make the garadget compatible with the nymea uuid is in global.h to change MAXNAMESIZE to 33 and PORT_BUFFER to 0x22 if you follow up on his suggestion. Also I could not get the Particle latest versions to work with the device. I had to regress to the Particle v2.0.1 version to have it work (this is the current version garadget uses as I understand). Obviously both of you know a lot more about this kind of programming than I do. And thank you yeti7.

**Comment by hi-flyer** [comment]
different question is the garadget "id" unique across all garadget devices?
I assume it is.

**Comment by yeti7** [comment]
Yes, device ID's are unique across all of the Particle ecosystem.
